# site settings
title: Cathy Teng
subtitle: powered by GitHub
email: chteng@princeton.edu
description: Cathy Teng
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Cathy Teng
street_address: 6789 Frist Campus Center
city: Princeton
state: NJ
zip_code: 08544
country: USA
phone: (408) 394-6614

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cathyteng17
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/cattyteng
linkedin_url: https://www.linkedin.com/in/cathyteng
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
